version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    restart: always 

  app:
    image: carrefourar-push-notifier:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - REDIS_URL=${REDIS_URL}
    command: npm run start
    ports:
      - '3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: 'redis:latest'
    ports:
      - '6379'
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
